### ISSUE TITLE
TNG: 1 Minute left announcement

### ISSUE THREAD

**Issue by MVarland** [actionquake/q2pro#203]
The 1 MINUTE LEFT announcement is given even if the roundtimelimit is less than one minute.

I tried with roundtimelimit 0.5 and the 1 MINUTE LEFT announcement is given instantly after ACTION! and the round was only ~35 seconds long..

Perhaps it should only be announced if the roundtimelimit is larger than 1?

**Comment by darkshade9** [comment]
This is also true for regular `timelimit`, if less than 1, it will announce as soon as all other criteria pass (LCA is over, for example)

Should this change also address `timelimit` ?

**Comment by darkshade9** [comment]
https://github.com/actionquake/q2pro/pull/204

**Comment by MVarland** [comment]
I guess it isn't bad if we also adjust timelimit(?)

My main concern was the 1 Minute left announcement every round that not only displays mid-screen but also covers footstep sounds right in the beginning after ACTION! If one wanted to only allow 1 minute rounds
