### ISSUE TITLE
Reduce time on dropped weapons/items despawning in bot servers

### ISSUE THREAD

**Issue by darkshade9** [actionquake/q2pro#220]
In DM mode, when players die, they drop weapons and items, which are Points of Interests for bots.  This can lead to all of the bots clustering in the same area because there are so many POI targets.

Proposal to reduce the time on the weapons/items despawning if bot_enable 1 and bots are in the server

**Comment by MVarland** [comment]
I think the MK23 and the knife stay longer than unique weapons and items?

Would making them be on the same timer as unique weapons & items help? I
guess maybe that would depend on the number of bots..

ons 16 okt. 2024 kl. 17:30 skrev Aaron Dean ***@***.***>:

**Comment by darkshade9** [comment]
> I think the MK23 and the knife stay longer than unique weapons and items? Would making them be on the same timer as unique weapons & items help? I guess maybe that would depend on the number of bots.. ons 16 okt. 2024 kl. 17:30 skrev Aaron Dean ***@***.***>:

I like the idea of despawning faster based on the amount of bots?

**Comment by darkshade9** [comment]
This isn't specific to DM modes, but it's most obvious in DM modes because teamplay rounds clean themselves up.  I suppose more accurately, it affects any non-round-based game modes, such as CTF, Espionage, TDM and DM

**Comment by darkshade9** [comment]
https://github.com/actionquake/q2pro/pull/222
Does not affect knives or pistols
